version: "{build}"
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    dotnet restore src/ElastaCloud.DataBricks.Sdk.sln

    cd src/ElastaCloud.DataBricks.Sdk

    dotnet housework setbuildnumber %CiVersion%  ../../build.ini

    dotnet housework author .\ElastaCloud.DataBricks.Sdk.csproj  ../../build.ini

    cd ../..
build:
  project: src/ElastaCloud.DataBricks.Sdk.sln
  verbosity: minimal
artifacts:
- path: src/ElastaCloud.DataBricks.Sdk/bin/**/*.nupkg
deploy: off